#! /usr/bin/env Rscript
(function() {
    t <- function(x) trimws(x, which = "right")
    cat("#! /usr/bin/env Rscript\n")
    cat("(", paste(t(deparse(call("function", NULL, body()))),
        collapse = "\n"), ")()\n", sep = "")
})()
